Добавлен фикс on_delete=models.CASCADE в модели с полем models.ForignKey что бы убрать ошибку : TypeError: __init__() missing 1 required positional argument: 'on_delete'